[project]
name = "modulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "priyash7", email = "priyashshah4@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
