[project]
name = "modulator"
version = "1.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
[[project.authors]]
name = "priyash7"
email = "priyashshah4@gmail.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"
