name: Version Bump

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - development

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python version
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11'

      - name: Install semantic-release
        run: |
          pip install python-semantic-release

      - name: Bump version in main project
        working-directory: ./verbump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version

      - name: Bump version in operator1 project
        working-directory: ./operators/modulator
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          cat pyproject.toml

      - name: Bump version in operator2 project
        working-directory: ./operators/power
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          cat pyproject.toml

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: bump project versions" || exit 0
          git push