name: Bump version

on: [push]

jobs:
  Bump-Package-Version:
    runs-on: ubuntu-latest

    steps:

      # Step 2: Get changed files
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Get latest commit message
        run: echo "${{ github.event.commits[0].message }} is the commit message!"

      - name: Print changed files
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done
      -name: Run python script
        run: |
          # Run python script now!
          python3 bump_version.py ${{ github.event.commits[0].message }} ${{ steps.files.outputs.all }}

