name: Bump version

on: [push]

jobs:
  Bump-Package-Version:
    runs-on: ubuntu-latest

    steps:

      # Step 2: Get changed files
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      # Step 3: Get latest commit message
      - name: Get latest commit message
        run: echo "COMMIT_MESSAGE=${{ github.event.commits[0].message }}" >> $GITHUB_ENV

      # Step 4: Format and process changed files
      - name: Process changed files
        id: process_files
        run: |
          # Extract changed files from JSON output
          CHANGED_FILES=$(echo "${{ steps.files.outputs.all }}" | jq -r '.[]' | tr '\n' ' ')
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      # Step 5: Run Python script with commit message and changed files
      - name: Run Python script
        run: |
          python3 bump_version.py "${{ env.COMMIT_MESSAGE }}" "${{ env.CHANGED_FILES }}"
