name: Bump version

on:
  push:
    branches:
      - main
      - development

jobs:
  Bump-Package-Version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Get all commit messages
        id: all_commit_messages
        run: echo "ALL_COMMIT_MESSAGES=${{ join(github.event.commits[*].message,',') }}"

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Display all files changed
        run: echo "${{ steps.files.outputs.all }}"
      
      - name: Set up python dependecnies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install toml

      - name: Run python script
        run: python3 .github/workflows/bump_version.py "${{ join(github.event.commits[*].message,',') }}" "${{ steps.files.outputs.all }}"