name: Bump version

on: [push]

jobs:
  Bump-Package-Version:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Get latest commit message
        run: echo "COMMIT_MESSAGE=${{ github.event.commits[0].message }}" 

      - name: Print changed files
        run: |
          for changed_file in ${{steps.file.outputs.all}}; do
            echo "Changed file: ${changed_file}."
          done

      - name: Run python script
        run: |
          python3 bump_version.py "${{ github.even.commits[0].message }}" "${{ steps.file.outputs.all }}"
