name: Version Bump

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - development

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check for changes in verbump
        id: check_verbump
        run: |
          CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- verbump)
          if [ -n "$CHANGES" ]; then
            echo "Changes detected in verbump"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in verbump"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes in operators/modulator
        id: check_modulator
        run: |
          CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- operators/modulator)
          if [ -n "$CHANGES" ]; then
            echo "Changes detected in modulator"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in modulator"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes in operators/power
        id: check_power
        run: |
          CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- operators/power)
          if [ -n "$CHANGES" ]; then
            echo "Changes detected in power"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in power"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Python version
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Install semantic-release
        run: |
          pip install python-semantic-release

      - name: Release main project
        if: steps.check_verbump.outputs.has_changes == 'true'
        uses: python-semantic-release/python-semantic-release@v9.12.0
        with:
          directory: ./verbump
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release modulator
        if: steps.check_modulator.outputs.has_changes == 'true'
        uses: python-semantic-release/python-semantic-release@v9.12.0
        with:
          directory: ./operators/modulator
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release main power
        if: steps.check_power.outputs.has_changes == 'true'
        uses: python-semantic-release/python-semantic-release@v9.12.0
        with:
          directory: ./operators/power
          github_token: ${{ secrets.GITHUB_TOKEN }}